### ISSUE TITLE
Don’t just check errors, handle them gracefully

### ISSUE THREAD

**Issue by yanpozka** [codeship/go-retro#3]
Compare strings to check errors is considered a very bad practice, like this example from the README:
```go
if err.Error() == "EOF" {
```
Instead I recommend this reading http://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

**Comment by bfosberry** [comment]
Totally, this is a readme, don't copy and paste to implement it

**Comment by bfosberry** [comment]
Added some more examples, took that out of the readme
