### ISSUE TITLE
Update Go-retro to support background workers, and goroutine handoff

### ISSUE THREAD

**Issue by bfosberry** [codeship/go-retro#8]
Currently this works in the case where we have a synchronous set of goroutines processing work, such as with a web handler. With a limited worker pool the sleep methodology of this library makes it inefficient. A better approach would be to support some kind of handoff and a future execution time determine by the error type returned, e.g.

```
// Wrap your code block with retro
finalErr, retryAt := retro.DoWithAsyncRetry(func() error{
    // Hit an external API
    return DoMyFunc(args)
})

if finalErr != nil {
  logger.Error("my stuff failed :(")
  return finalErr
}

// code did not complete, need to retry
if retryAt != nil {
  // if Im using a worker queue I can specify that this task should not be handled until this time
  time.Sleep(*retryAt - time.Now())
  // try again, but in a more reusable way than this
  finalErr, retryAt := retro.DoWithAsyncRetry(func() error{
    // Hit an external API
    return DoMyFunc(args)
  })
} else {
  // error was nil, no retry needed
  return nil
}
```

**Comment by markphelps** [comment]
Thanks for the issue, however we are no longer maintaining this library so we will be archiving it. Please feel free to fork it if you would still like to make this change.
