### ISSUE TITLE
infinite retries

### ISSUE THREAD

**Issue by targence** [codeship/go-retro#9]
I am suggesting add infinite retries feature.
For example if we use `-1` in NewStaticRetryableError.

```
ErrNetwork = retro.NewStaticRetryableError(errors.New("error: Max retries attempts reached"), -1, 2)
```

**Comment by markphelps** [comment]
Thanks for the issue, however we are no longer maintaining this library so we will be archiving it. Please feel free to fork it if you would still like to make this change.
